#!/usr/bin/env bash
set -e

rebar3 release

rm -rf _etwas
mkdir -p _etwas

nix-build release.nix -o _etwas/result

cd _etwas

etwas result "blatus-release"

tar -cavf "blatus-release.tgz" "blatus-release"
