name: "Blatus CI"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    container: catthehacker/ubuntu:runner-latest
    env: 
      USER: robashton
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v13
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - run: nix-build

